;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-force-normal-state
        evil-insert
        evil-next-visual-line
        evil-normal-state
        evil-previous-visual-line
        evil-yank
        ))

(setq mc/cmds-to-run-once
      '(
        ))
